export const INIT_APP_REQUEST = 'INIT_APP_REQUEST';
export const INIT_APP_SUCCESS = 'INIT_APP_SUCCESS';
export const INIT_APP_FAILURE = 'INIT_APP_FAILURE';

export const SET_MOBILE_STATUS = 'SET_MOBILE_STATUS';


export const GET_AIRPORT_NAMES = 'GET_AIRPORT_NAMES';
export const SET_AIRPORT_NAMES = 'SET_AIRPORT_NAMES';

export const GET_FLIGHTS_ROUTES = 'GET_FLIGHTS_ROUTES';
export const SET_FLIGHTS_ROUTES = 'SET_FLIGHTS_ROUTES';